### Create a new post
POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "How to cassandra",
     "description": "Learn how to cassandra",
      "author": "John Doe",
      "url": "/how-to-cassandra/",
      "tags": ["cassandraDB", "Database", "Learn"],
      "likes": 10,
      "emojis": [{ "name": "thumbsup" }, { "name": "star" }]
}


### Create a new post with file upload
POST http://localhost:3000/posts/image
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="title"

How to Mongo
--boundary
Content-Disposition: form-data; name="description"

Learn how to Mongo
--boundary
Content-Disposition: form-data; name="author"

John Doe
--boundary
Content-Disposition: form-data; name="image"; filename="sample.png"
Content-Type: image/png

< C:\Users\cselab2-01\Desktop\sample.png
--boundary--



### Get all posts
GET http://localhost:3000/posts

### Get a specific post by ID
# Replace <postId> with an actual post ID after creating a post
GET http://localhost:3000/posts/66a0bb874adcd17880282cd3

### Update a specific post by ID
# Replace <postId> with an actual post ID after creating a post
PATCH http://localhost:3000/posts/66a0bb874adcd17880282cd3
Content-Type: application/json

{
         "title": "Updated Title",
         "description": "Updated Description",
         "author": "Updated Author",
         "url": "/updated-url/",
         "tags": ["UpdatedTag1", "UpdatedTag2"],
         "likes": 20,
         "emojis": [{ "name":  "ok" }, { "name":  "fine" }]
}


### Delete a specific post by ID
# Replace <postId> with an actual post ID after creating a post
DELETE http://localhost:3000/posts/66a1cd9c5a3b7e739461cf64


### Get all posts with pagination
# Adjust page and limit parameters as needed
GET http://localhost:3000/posts?page=1&limit=2
